apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS cruddb;
    USE cruddb;

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        email VARCHAR(100),
        mobile VARCHAR(15)
    );

    INSERT INTO users (name, email, mobile)
    VALUES ('Arun M L', 'aarjaappu@outlook.com', '7087046932');
