apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-crud
  template:
    metadata:
      labels:
        app: php-crud
    spec:
      containers:
      - name: php-crud
        image: gangassault343/myphpmysqlapp:v2
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath:  metadata.name  
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-crud
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
