apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/mysql  # Key insight, hostPath = node-local storage. So:Data exists only on the node where Pod runs,Not visible on other nodes
